### ISSUE TITLE
CommentBox Still going on ?

### ISSUE THREAD

**Issue by subodhcjoshi82** [nickrussler/commentbox#10]
Hi I saw your main website http://nickrussler.github.io/commentbox/ but few link are not working. Is this component alive or its dead now?

**Comment by nickrussler** [comment]
Since there was not much interest i stopped actively maintaining it.

**Comment by subodhcjoshi82** [comment]
Thanks for your quick reply..but 2013  i heard it will be a part of PF what happened its still alone going on.  As PF6.0 is going on will it support latest release as well?

**Comment by nickrussler** [comment]
The devs of Primefaces suggested that it could be part of Primefaces Extensions, but since it is a composite component they refused. As i said i don't activly maintain this project right now, therefore i don't know if PF 6 is supported, but i would welcome any pull requests!

**Comment by subodhcjoshi82** [comment]
As i am thinking to this to one the project i am going to start ,will you fix the issue if i will raise ? As i am thinking to use Latest PF and JSF.
