### ISSUE TITLE
Getting Exception when running the demo-source code ?

### ISSUE THREAD

**Issue by subodhcjoshi82** [nickrussler/commentbox#11]
I am getting below exception

> SEVERE: Error Rendering View[/index.xhtml]
> javax.el.ELException: /file:/C:/MyWorld/workspace1/.metadata/.plugins/org.eclipse.wst.server.core/tmp3/wtpwebapps/commentbox-demo/WEB-INF/lib/commentbox-0.0.1-SNAPSHOT.jar!/META-INF/resources/composites/commentBox.xhtml @100,143 value="#{cc.tree}": Error reading 'tree' on type info.whitebyte.component.commentbox.CommentBox
>   at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:114)
>   at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
>   at org.primefaces.component.api.UITree.getValue(UITree.java:100)
>   at org.primefaces.component.api.UITree.visitNodes(UITree.java:460)
>   at org.primefaces.component.api.UITree.visitTree(UITree.java:411)
>   at javax.faces.component.UIComponent.visitTree(UIComponent.java:1623)
>   at javax.faces.component.UIComponent.visitTree(UIComponent.java:1623)
>   at javax.faces.component.UIComponent.visitTree(UIComponent.java:1623)
>   at javax.faces.component.UIComponent.visitTree(UIComponent.java:1623)
>   at javax.faces.component.UIComponent.visitTree(UIComponent.java:1623)
>   at javax.faces.component.UINamingContainer.visitTree(UINamingContainer.java:163)
>   at javax.faces.component.UIComponent.visitTree(UIComponent.java:1623)
>   at javax.faces.component.UIComponent.visitTree(UIComponent.java:1623)
>   at com.sun.faces.application.view.FormOmittedChecker.check(FormOmittedChecker.java:91)
>   at com.sun.faces.application.view.FaceletViewHandlingStrategy.renderView(FaceletViewHandlingStrategy.java:419)
>   at com.sun.faces.application.view.MultiViewHandler.renderView(MultiViewHandler.java:125)
>   at com.sun.faces.lifecycle.RenderResponsePhase.execute(RenderResponsePhase.java:121)
>   at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:101)
>   at com.sun.faces.lifecycle.LifecycleImpl.render(LifecycleImpl.java:139)
>   at javax.faces.webapp.FacesServlet.service(FacesServlet.java:594)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>   at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
>   at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
>   at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
>   at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
>   at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
>   at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
>   at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
>   at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
>   at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
>   at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
>   at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
>   at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1079)
>   at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
>   at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
>   at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
>   at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
>   at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
>   at java.lang.Thread.run(Unknown Source)
> Caused by: com.sun.faces.mgbean.ManagedBeanCreationException: An error occurred performing resource injection on managed bean articleView
>   at com.sun.faces.mgbean.BeanBuilder.invokePostConstruct(BeanBuilder.java:229)
>   at com.sun.faces.mgbean.BeanBuilder.build(BeanBuilder.java:105)
>   at com.sun.faces.mgbean.BeanManager.createAndPush(BeanManager.java:409)
>   at com.sun.faces.mgbean.BeanManager.create(BeanManager.java:269)
>   at com.sun.faces.el.ManagedBeanELResolver.resolveBean(ManagedBeanELResolver.java:244)
>   at com.sun.faces.el.ManagedBeanELResolver.getValue(ManagedBeanELResolver.java:116)
>   at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
>   at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
>   at org.apache.el.parser.AstIdentifier.getValue(AstIdentifier.java:71)
>   at org.apache.el.parser.AstValue.getValue(AstValue.java:160)
>   at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
>   at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
>   at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:194)
>   at javax.faces.component.ComponentStateHelper.eval(ComponentStateHelper.java:182)
>   at info.whitebyte.component.commentbox.CommentBox.getAttribute(CommentBox.java:78)
>   at info.whitebyte.component.commentbox.CommentBox.getComments(CommentBox.java:92)
>   at info.whitebyte.component.commentbox.CommentBox.initTree(CommentBox.java:411)
>   at info.whitebyte.component.commentbox.CommentBox.getTree(CommentBox.java:441)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at javax.el.BeanELResolver.getValue(BeanELResolver.java:99)
>   at com.sun.faces.el.DemuxCompositeELResolver._getValue(DemuxCompositeELResolver.java:176)
>   at com.sun.faces.el.DemuxCompositeELResolver.getValue(DemuxCompositeELResolver.java:203)
>   at org.apache.el.parser.AstValue.getValue(AstValue.java:183)
>   at org.apache.el.ValueExpressionImpl.getValue(ValueExpressionImpl.java:184)
>   at com.sun.faces.facelets.el.ContextualCompositeValueExpression.getValue(ContextualCompositeValueExpression.java:156)
>   at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:109)
>   ... 39 more
> Caused by: com.sun.faces.spi.InjectionProviderException
>   at com.sun.faces.vendor.WebContainerInjectionProvider.invokeAnnotatedMethod(WebContainerInjectionProvider.java:116)
>   at com.sun.faces.vendor.WebContainerInjectionProvider.invokePostConstruct(WebContainerInjectionProvider.java:96)
>   at com.sun.faces.mgbean.BeanBuilder.invokePostConstruct(BeanBuilder.java:223)
>   ... 67 more
> Caused by: java.lang.reflect.InvocationTargetException
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at com.sun.faces.vendor.WebContainerInjectionProvider.invokeAnnotatedMethod(WebContainerInjectionProvider.java:114)
>   ... 69 more
> Caused by: java.lang.NullPointerException
>   at view.backingbeans.ArticleView.loadRootComments(ArticleView.java:35)
>   at view.backingbeans.ArticleView.init(ArticleView.java:41)
>   ... 74 more

I am running it in Tomcat7+/Java7+ also you can check attached screen shot 

![test](https://cloud.githubusercontent.com/assets/2179755/18520258/bd43c4b8-7ac4-11e6-81bc-7a93de02f731.PNG)

**Comment by nickrussler** [comment]
Hi, I am very sorry, but this project is not maintained anymore..

**Comment by subodhcjoshi82** [comment]
Hi Thanks for your quick reply I have to use this component in my big project so do you mean i should not use this component ?

**Comment by nickrussler** [comment]
If you don't plan to maintain this code (fork or send me PRs) then I would recommend against it.

**Comment by subodhcjoshi82** [comment]
I am new in Git can you please let me know what is this PRs ?

**Comment by nickrussler** [comment]
A pull request (see [here](https://help.github.com/articles/about-pull-requests/) or [here](https://www.youtube.com/watch?v=FQsBmnZvBdc)).

**Comment by subodhcjoshi82** [comment]
I am getting 

There isn’t anything to compare.

nickrussler:master and subodhcjoshi82:master are identical.

**Comment by nickrussler** [comment]
Yes, since you didn't commit any changes. What I meant is that i would not recommend you to use this component unless you are willing to maintain it yourself and commit these changes to your forked repository. It would be nice if you would send these changes to me through pull requests then.

**Comment by subodhcjoshi82** [comment]
But right now i am struggling to check the how its working then how would i commit any changes in future if i will make any changes i will surely make commit or update you or take guidance from you my changes because any how u are sole owner of this component

**Comment by nickrussler** [comment]
Thank you very much.

**Comment by subodhcjoshi82** [comment]
I did not get thanks for what ? I would be thankful for your work not you. Any how any update about the issue

**Comment by nickrussler** [comment]
As I said I don't maintain this project anymore, you are on your own. Sorry.
